name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Run E2E tests
        run: npm run test:e2e:run
